# Generated by Django 5.1.4 on 2024-12-19 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vikes_reading_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='answers_given',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='progress',
            name='score',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['student'], name='vikes_readi_student_f59a45_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['read_story'], name='vikes_readi_read_st_f88014_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['story'], name='vikes_readi_story_i_c0d8ac_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['author'], name='vikes_readi_author__79b734_idx'),
        ),
    ]
