# Generated by Django 5.1.4 on 2024-12-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vikes_reading_app', '0003_alter_answer_answer_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='english_level',
        ),
        migrations.RemoveField(
            model_name='story',
            name='english_level',
        ),
        migrations.AddField(
            model_name='story',
            name='narration_audio',
            field=models.FileField(blank=True, null=True, upload_to='story_audio/'),
        ),
    ]
