# Generated by Django 5.1.4 on 2024-12-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vikes_reading_app', '0005_prereadingexercise'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='progress',
            name='vikes_readi_student_f59a45_idx',
        ),
        migrations.RemoveIndex(
            model_name='progress',
            name='vikes_readi_read_st_f88014_idx',
        ),
        migrations.AddField(
            model_name='progress',
            name='current_stage',
            field=models.CharField(choices=[('pre_reading', 'Pre-Reading'), ('reading', 'Reading'), ('post_reading', 'Post-Reading'), ('completed', 'Completed')], default='pre_reading', max_length=20),
        ),
    ]
