# Generated by Django 5.1.4 on 2025-03-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('vikes_reading_app', '0008_story_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prereadingexercise',
            name='category',
        ),
        migrations.RemoveField(
            model_name='prereadingexercise',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='prereadingexercise',
            name='is_option_1_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prereadingexercise',
            name='is_option_2_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
