# Generated by Django 5.1.4 on 2025-03-16 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vikes_reading_app', '0009_remove_prereadingexercise_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prereadingexercise',
            name='order',
        ),
    ]
