# Generated by Django 5.1.4 on 2025-03-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vikes_reading_app', '0010_remove_prereadingexercise_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='post_reading_time',
            field=models.IntegerField(default=0, help_text='Time in seconds'),
        ),
        migrations.AddField(
            model_name='progress',
            name='pre_reading_time',
            field=models.IntegerField(default=0, help_text='Time in seconds'),
        ),
        migrations.AddField(
            model_name='progress',
            name='reading_time',
            field=models.IntegerField(default=0, help_text='Time in seconds'),
        ),
    ]
