# Generated by Django 5.1.4 on 2025-03-30 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vikes_reading_app', '0012_remove_question_story_postreadingquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreadingquestion',
            name='order',
        ),
    ]
