# Generated by Django 5.1.4 on 2025-04-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vikes_reading_app', '0013_remove_postreadingquestion_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='post_reading_lookups',
            field=models.JSONField(default=dict),
        ),
    ]
