# Generated by Django 5.1.4 on 2026-03-16 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vikes_reading_app', '0014_progress_post_reading_lookups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='score',
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
    ]
